runtime: python39
default_expiration: "1d"

handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto