steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "Deploy App Engine"
  args:
    [
      "app",
      "deploy",
      "app.yaml",
      "--bucket=gs://jpoirierlavoie-ca.appspot.com",
      "--cache",
      "--promote",
      "--stop-previous-version"
    ]
